version: '3'  # Compose file format version
services:

  hoverfly:
    image: spectolabs/hoverfly:v1.11.1
    ports:
      - "8500:8500"
      - "8888:8888"
    volumes:
      - "./simulations:/hoverfly/simulations"
    command:
      - "-import"
      - "/hoverfly/simulations/${IMPORT_FILE:-streamed.json}"
      - "-webserver"

  node-proxy:
    image: node:latest
    volumes:
      - ".:/node-proxy"
    command: ["node", "/node-proxy/Myserver.js"]
    ports:
      - "3000:3000"
    depends_on:
      - hoverfly